const data = [
  {
    name: '"Introduction to AI',
    price: ' Machine Learning and Data Science 2021"',
    description: '455',
    host: '"Introductory Course for Beginners to AI',
    rating: ' Machine Learning',
    duration: ' Data Science',
    lectures: ' Deep Learning',
    level: ' Supervised and Unsupervised ML"',
    url: 'Pradeep D',
  },
  {
    name: 'Data Science A-Z : Machine Learning with Python & R',
    price: '455',
    description:
      'By Data Scientist / IITian for Beginners . Data Science/Machine Learning with Python & R for beginners to advance',
    host: 'Arpan Gupta',
    rating: '3.6',
    duration: '12.5 total hours',
    lectures: '90 lectures',
    level: 'All Levels',
    url: 'https://www.udemy.com/course/machine-learning-using-r/\r',
  },
  {
    name: 'Introduction To Data Science',
    price: '455',
    description:
      'Use the R Programming Language to execute data science projects and become a data scientist.',
    host: '"Nina Zumel',
    rating: ' John Mount"',
    duration: '3.6',
    lectures: '6 total hours',
    level: '28 lectures',
    url: 'Intermediate',
  },
  {
    name: 'SQL for Data Analysis and Data Science in 2021',
    price: '455',
    description: '"SQL by SQL example',
    host: ' SQL Challenges& SQL Final Exam using Real World SQL Database for Data Science & Data Analysis"',
    rating: 'Tamer Ahmed',
    duration: '3.7',
    lectures: '5.5 total hours',
    level: '114 lectures',
    url: 'All Levels',
  },
  {
    name: 'The 2021 Absolute Beginners Guide to Data Science',
    price: '455',
    description:
      'Build your mathematics and statistics foundations strongly and ensure your Data science fundamentals are in place!',
    host: 'Sai Acuity Institute of Learning Pvt Ltd Enabling Learning Through Insight!',
    rating: '3.7',
    duration: '41.5 total hours',
    lectures: '50 lectures',
    level: 'Beginner',
    url: 'https://www.udemy.com/course/the-absolute-beginners-guide-to-data-science/\r',
  },
  {
    name: 'R Programming Hands-on Specialization for Data Science (Lv1)',
    price: '455',
    description:
      'An in-depth course on R language with real-world Data Science examples to supercharge your R data analysis skills',
    host: 'Irfan Elahi',
    rating: '3.7',
    duration: '11 total hours',
    lectures: '87 lectures',
    level: 'Beginner',
    url: 'https://www.udemy.com/course/r-programming-data-science-hands-on-course/\r',
  },
  {
    name: 'What is Data Science?',
    price: '455',
    description:
      'Build your mathematics and statistics foundations strongly and ensure your Data science fundamentals are in place!',
    host: 'Sai Acuity Institute of Learning Pvt Ltd Enabling Learning Through Insight!',
    rating: '3.8',
    duration: '4.5 total hours',
    lectures: '8 lectures',
    level: 'All Levels',
    url: 'https://www.udemy.com/course/what-is-data-science-r/\r',
  },
  {
    name: 'Python for Data Science and Data Analysis Masterclass: 2021',
    price: '455',
    description: '"Learn Python for Data Science',
    host: ' Machine Learning',
    rating: ' Deep Learning & Data Analysis',
    duration: " Hand's on NumPy",
    lectures: ' Pandas and Matplotlib !"',
    level: 'Vijay Gadhave',
    url: '3.9',
  },
  {
    name: 'Data Science with Python Certification Training and Project',
    price: '566',
    description:
      'Start your career as Data Scientist from scratch. Learn Data Science with Python. Predict trends with advanced analytics',
    host: 'Uplatz Training',
    rating: '3.9',
    duration: '44.5 total hours',
    lectures: '56 lectures',
    level: 'All Levels',
    url: 'https://www.udemy.com/course/data-science-with-python-certification-training/\r',
  },
  {
    name: 'Colors for Data Science A-Z: Data Visualization Color Theory',
    price: '455',
    description:
      'Learn how to apply colour theory to improve your Data Science & Analytics data visualisations and presentations',
    host: '"Kirill Eremenko',
    rating: ' Patrycja Angelika Jeleniewicz',
    duration: ' Ligency Team"',
    lectures: '4',
    level: '4 total hours',
    url: '34 lectures',
  },
  {
    name: 'Data Science and Machine Learning with Python and Libraries',
    price: '455',
    description:
      '"Learn Data Science and Machine Learning with Python and Libraries such as Numpy',
    host: ' Matplotlib',
    rating: ' Pandas and much more"',
    duration: 'The Tech X Learners',
    lectures: '4',
    level: '7 total hours',
    url: '74 lectures',
  },
  {
    name: 'R Programming:For Data Science With Real Exercises',
    price: '455',
    description: '"Learn Programming In R And R Studio. Data Analytics',
    host: ' Data Science',
    rating: ' Statistical Analysis',
    duration: ' Packages',
    lectures: ' Functions',
    level: ' GGPlot2"',
    url: 'Zulqarnain Hayat',
  },
  {
    name: 'Data Science with R - Beginners',
    price: '455',
    description:
      'This training is an introduction to the concept of Data science and its application using R programming language',
    host: 'SimpliCode Point',
    rating: '4',
    duration: '6 total hours',
    lectures: '56 lectures',
    level: 'All Levels',
    url: 'https://www.udemy.com/course/data-science-with-r-beginners/\r',
  },
  {
    name: 'Data Science Course 2021: Complete Machine Learning Training',
    price: '455',
    description:
      '"Build a Career in Artificial Intelligence (AI). Hands-on Training with ""7 Stages of Machine Learning"" Framework."',
    host: 'Data-Driven Science',
    rating: '4.1',
    duration: '19 total hours',
    lectures: '218 lectures',
    level: 'All Levels',
    url: 'https://www.udemy.com/course/datadrivenscience-machinelearning/\r',
  },
  {
    name: 'Introduction To Data Science',
    price: '455',
    description: 'Data Science from the very basics',
    host: 'Sahla Ali',
    rating: '4.1',
    duration: '1 total hour',
    lectures: '19 lectures',
    level: 'Intermediate',
    url: 'https://www.udemy.com/course/introduction-to-data-science-basics/\r',
  },
  {
    name: 'Statistics for Data Science using Python',
    price: '455',
    description: '"Statistics you need in the office: Core of Statistics',
    host: ' Inferential & Descriptive statistics',
    rating: ' Hypothesis testing',
    duration: '"',
    lectures: 'Shan Singh',
    level: '4.1',
    url: '8 total hours',
  },
  {
    name: "A Beginner's Guide to Machine Learning (in Python)",
    price: '455',
    description: '"Learn supervised learning for structured data',
    host: ' and implement them using Python programming"',
    rating: 'Curiosity for Data Science',
    duration: '4.1',
    lectures: '3.5 total hours',
    level: '49 lectures',
    url: 'All Levels',
  },
  {
    name: '"Python required for AI',
    price: ' Machine Learning & Data Science 2021"',
    description: '566',
    host: '"numpy',
    rating: ' pandas',
    duration: ' matplotlib',
    lectures: ' seaborn',
    level: ' machine learning',
    url: ' data science',
  },
  {
    name: 'Python for Data Science and Machine Learning',
    price: '"1',
    description: '920"',
    host: 'A Practical Approach Learn by Implementing',
    rating: 'Kumar Rajmani Bapat',
    duration: '4.1',
    lectures: '7 total hours',
    level: '19 lectures',
    url: 'All Levels',
  },
  {
    name: 'Python Bootcamp 2021 Build 15 working Applications and Games',
    price: '455',
    description: '"Learn complete python with basics',
    host: ' data science',
    rating: ' data visualisation',
    duration: ' desktop graphical applications and python for web."',
    lectures: 'Dev Nirwal',
    level: '4.2',
    url: '32 total hours',
  },
  {
    name: 'Python-Introduction to Data Science and Machine learning A-Z',
    price: '455',
    description:
      'Python basics Learn Python for Data Science Python For Machine learning and Python Tips and tricks',
    host: 'Yassin Marco',
    rating: '4.2',
    duration: '7.5 total hours',
    lectures: '51 lectures',
    level: 'Beginner',
    url: 'https://www.udemy.com/course/python-introduction-to-data-science-and-machine-learning-a-z/\r',
  },
  {
    name: '"Learn Data Science Deep Learning',
    price: ' Machine Learning NLP & R"',
    description: '455',
    host: '"Learn Data Science',
    rating: ' Deep Learning',
    duration: ' Machine Learning',
    lectures: ' Natural Language Processing',
    level: ' R and Python Language with libraries"',
    url: 'Cinnamon TechX',
  },
  {
    name: 'Python & Introduction to Data Science',
    price: '819',
    description:
      'Learn the basics of Python and the most important Data Science libraries with this step by step guide!',
    host: 'AI 4 MY',
    rating: '4.2',
    duration: '9 total hours',
    lectures: '68 lectures',
    level: 'Beginner',
    url: 'https://www.udemy.com/course/python-introduction-to-data-science/\r',
  },
  {
    name: 'Docker Masterclass for Machine Learning and Data Science',
    price: '455',
    description:
      'Learn how to containerize and deploy your ML projects with Docker',
    host: '"Jordan Sauchuk',
    rating: ' Ligency Team"',
    duration: '4.2',
    lectures: '4.5 total hours',
    level: '82 lectures',
    url: 'All Levels',
  },
  {
    name: 'Statistics & Applied Data Science - Business Data Analysis',
    price: '566',
    description:
      '"Data Science Statistics : Data Science from Scratch for Beginners : Data Analysis Techniques',
    host: ' Method Course : Analytics"',
    rating: 'Mahmoud Ali',
    duration: '4.2',
    lectures: '9 total hours',
    level: '272 lectures',
    url: 'All Levels',
  },
  {
    name: 'Ultimate Python Bootcamp For Data Science & Machine Learning',
    price: '455',
    description: '"Learn How To Code Python For Data Science',
    host: ' ML & Data Analysis',
    rating: ' With 100+ Exercises and 4 Real Life Projects !"',
    duration: 'Pruthviraja L',
    lectures: '4.2',
    level: '16 total hours',
    url: '103 lectures',
  },
  {
    name: 'Data Science and Machine Learning For Beginners with Python',
    price: '455',
    description: '"Learn to Analyse ',
    host: ' Make Predictions',
    rating: ' Explore data Frames',
    duration: 'Clean and Visualize Data"',
    lectures: 'Bluelime Learning Solutions',
    level: '4.2',
    url: '8 total hours',
  },
  {
    name: 'Complete Data Science & Machine Learning Bootcamp in Python',
    price: '566',
    description: '"Learn Python',
    host: 'NumPy',
    rating: 'Pandas',
    duration: 'Matplotlib',
    lectures: 'Seaborn',
    level: 'Scikit-learn',
    url: 'Dask',
  },
  {
    name: 'Beginning with Machine Learning & Data Science in Python',
    price: '455',
    description:
      '"Fundamentals of Data Science : Exploratory Data Analysis (EDA)',
    host: ' Regression (Linear & logistic)',
    rating: ' Visualization',
    duration: ' Basic ML"',
    lectures: 'UNP United Network of Professionals',
    level: '4.2',
    url: '3.5 total hours',
  },
  {
    name: 'Complete Data Wrangling & Data Visualisation With Python',
    price: '455',
    description: '"Learn to Preprocess',
    host: ' Wrangle and Visualise Data For Practical Data Science Applications in Python"',
    rating: 'Minerva Singh',
    duration: '4.2',
    lectures: '6 total hours',
    level: '52 lectures',
    url: 'All Levels',
  },
  {
    name: 'Full Stack Data Science Course - Become a Data Scientist',
    price: '455',
    description:
      'Master the four major areas of Data Science and become a Full Stack Data Scientist in 2021.',
    host: '"The Click Reader',
    rating: ' Merishna Singh Suwal"',
    duration: '4.2',
    lectures: '2 total hours',
    level: '33 lectures',
    url: 'All Levels',
  },
  {
    name: 'Learn Big Data(Spark) for Data Science�Machine Learning &NLP',
    price: '455',
    description:
      '"Learn Big Data - Hadoop-Spark/PySpark & Data Science from basics of Stats',
    host: 'Machine Learning',
    rating: 'NLP using Spark :AllLevels"',
    duration: 'Srini E',
    lectures: '4.2',
    level: '22 total hours',
    url: '127 lectures',
  },
  {
    name: 'Tensorflow Deep Learning - Data Science in Python',
    price: '455',
    description:
      'Tensorflow Deep Learning Python : Tensorflow Neural Network Training : Tensorflow Models - Android Java : Tensorflow C#',
    host: 'Minerva Singh',
    rating: '4.2',
    duration: '7 total hours',
    lectures: '69 lectures',
    level: 'All Levels',
    url: 'https://www.udemy.com/course/tensorflow-bootcamp-for-data-science-in-python/\r',
  },
  {
    name: 'Python Programming for Beginners in Data Science',
    price: '455',
    description:
      '"This Python for beginners course teaches you ""just enough"" python training online with Python 3 for Data Science"',
    host: 'Ajay Tech',
    rating: '4.3',
    duration: '14 total hours',
    lectures: '105 lectures',
    level: 'Beginner',
    url: 'https://www.udemy.com/course/just-enough-python/\r',
  },
  {
    name: 'Python for Data Science and Machine Learning beginners',
    price: '585',
    description: '"A Complete Machine learning Bootcamp learn Numpy',
    host: ' Pandas',
    rating: ' Matplotlib',
    duration: ' Stats',
    lectures: ' Plotly ',
    level: ' EDA ',
    url: ' Scikit-learn and more!"',
  },
  {
    name: '2021 Data Science/MachineLearning Project Deployment Mastery',
    price: '455',
    description:
      '"Learn Data Science/ML with 20+Practical Hands-On Projects and Deployment.(Flask',
    host: 'Heroku',
    rating: 'AWS',
    duration: 'Google Cloud',
    lectures: 'Microsoft Azure)"',
    level: 'MrBriit .',
    url: '4.3',
  },
  {
    name: 'Data Science Real World Projects in Python',
    price: '455',
    description: '"Solve 3 real Business Problems',
    host: ' Build Robust AI',
    rating: ' Ml ',
    duration: ' NLP and Time Series models for Airline',
    lectures: ' Security & Stock Domain.."',
    level: 'Shan Singh',
    url: '4.3',
  },
  {
    name: 'Introduction to Data Science',
    price: '455',
    description:
      '"An overview of modern data science: the practice of obtaining',
    host: ' exploring',
    rating: ' modeling',
    duration: ' and interpreting data."',
    lectures: 'Data Hawk Tech',
    level: '4.3',
    url: '3 total hours',
  },
  {
    name: 'Python and Data Science for beginners',
    price: '455',
    description: 'Learn hands-on data science and Python from scratch',
    host: 'Bluelime Learning Solutions',
    rating: '4.3',
    duration: '4.5 total hours',
    lectures: '39 lectures',
    level: 'Beginner',
    url: 'https://www.udemy.com/course/introduction-to-data-science-with-python-for-beginners/\r',
  },
  {
    name: 'Data Analysis Bootcamp� 21 Real World Case Studies',
    price: '455',
    description: '"Gain Business Intelligence Skills using Statistics',
    host: ' Data Wrangling',
    rating: ' Data Science',
    duration: ' Visualizations & Google Data Studio"',
    lectures: '"Rajeev D. Ratan',
    level: ' Nidia Sahjara"',
    url: '4.3',
  },
  {
    name: 'Data Science Masterclass With R 8 Case Studies + 4 Projects',
    price: '455',
    description: '"Data Science by IITian -Data Science+R Programming ',
    host: 'Data analysis',
    rating: ' Data Visualization',
    duration: ' Data Pre-processing etc"',
    lectures: 'Up Degree',
    level: '4.3',
    url: '32 total hours',
  },
  {
    name: 'Probability for Statistics and Data Science',
    price: '455',
    description: '"Probability for improved business decisions: Introduction',
    host: ' Combinatorics',
    rating: ' Bayesian Inference',
    duration: ' Distributions"',
    lectures: '365 Careers',
    level: '4.3',
    url: '3.5 total hours',
  },
  {
    name: 'Alteryx: Data Science for Non-Scientists',
    price: '"1',
    description: '920"',
    host: '"Designed specifically for beginners with no background in Data Science',
    rating: ' Computer Science or Alteryx"',
    duration: 'Jed Guinto',
    lectures: '4.3',
    level: '5 total hours',
    url: '36 lectures',
  },
  {
    name: 'Data Science: Beginners Guide to the Command Line',
    price: '455',
    description:
      'Master the Basics of the Command Line and Prepare for a Career in Data Science!',
    host: 'Ben Weinstein',
    rating: '4.3',
    duration: '1.5 total hours',
    lectures: '32 lectures',
    level: 'All Levels',
    url: 'https://www.udemy.com/course/data-science-beginners-guide-to-the-command-line/\r',
  },
  {
    name: 'Python for Data Science',
    price: '455',
    description: '"An introductory to intermediate level program in Python',
    host: ' and how to apply it in data science"',
    rating: '"Starweaver Team',
    duration: ' Paul Siegel"',
    lectures: '4.3',
    level: '9 total hours',
    url: '59 lectures',
  },
  {
    name: 'Calculus - Mathematics for Data Science - Machine Learning',
    price: '455',
    description:
      'Mastering Calculus - Mathematics for Deep learning / Machine learning / Data Science / Data Analysis / AI - Hands On',
    host: 'Manifold AI Learning �',
    rating: '4.3',
    duration: '10 total hours',
    lectures: '105 lectures',
    level: 'Intermediate',
    url: 'https://www.udemy.com/course/deep-learning-calculus-data-science-machine-learning-ai/\r',
  },
  {
    name: 'Introduction to Machine Learning for Data Science',
    price: '566',
    description:
      '"A primer on Machine Learning for Data Science. Revealed for everyday people',
    host: ' by the Backyard Data Scientist."',
    rating: 'David Valentine',
    duration: '4.4',
    lectures: '5.5 total hours',
    level: '62 lectures',
    url: 'Beginner',
  },
  {
    name: 'Artificial Intelligence A-Z�: Learn How To Build An AI',
    price: '455',
    description: '"Combine the power of Data Science',
    host: ' Machine Learning and Deep Learning to create powerful AI for Real-World applications!"',
    rating: '"Hadelin de Ponteves',
    duration: ' Kirill Eremenko',
    lectures: ' SuperDataScience Support',
    level: ' Luka Anicin',
    url: ' Ligency Team"',
  },
  {
    name: 'Complete Data Analysis with Pandas : Hands-on Pandas Python',
    price: '455',
    description: '"Learn in demand skill Pandas',
    host: ' Sci-kit Learn',
    rating:
      ' Numpy For Data Science & Machine Learning : Seaborn | MatplotLib | Python"',
    duration: 'Data Science & Machine Learning Academy',
    lectures: '4.4',
    level: '17 total hours',
    url: '150 lectures',
  },
  {
    name: 'Complete Data Science Training with Python for Data Analysis',
    price: '455',
    description:
      'Beginners python data analytics : Data science introduction : Learn data science : Python data analysis methods tutorial',
    host: 'Minerva Singh',
    rating: '4.4',
    duration: '13 total hours',
    lectures: '123 lectures',
    level: 'All Levels',
    url: 'https://www.udemy.com/course/complete-data-science-training-with-python-for-data-analysis/\r',
  },
  {
    name: 'Data Science & Deep Learning for Business� 20 Case Studies',
    price: '455',
    description: '"Use Python to solve problems in Retail',
    host: ' Marketing',
    rating: ' Product Recommendation',
    duration: ' Customer Clustering',
    lectures: ' NLP',
    level: ' Forecasting & more!"',
    url: '"Rajeev D. Ratan',
  },
  {
    name: '"Data Science',
    price: ' Analytics & AI for Business & the Real World�"',
    description: '455',
    host: 'Use Data Science & Statistics To Solve Business Problems & Gain Insights Into Everyday Problems With 35+ Case Studies',
    rating: '"Rajeev D. Ratan',
    duration: ' Nidia Sahjara"',
    lectures: '4.4',
    level: '29.5 total hours',
    url: '244 lectures',
  },
  {
    name: '2021 Python for Data Science & Machine Learning from A-Z',
    price: '455',
    description:
      '"Become a professional Data Scientist and learn how to use NumPy',
    host: ' Pandas',
    rating: ' Machine Learning and more!"',
    duration: '"Juan E. Galvan',
    lectures: ' Ahmed Wael"',
    level: '4.4',
    url: '23 total hours',
  },
  {
    name: 'Complete Linear Algebra for Data Science & Machine Learning',
    price: '455',
    description: '"Linear Algebra for Data Science',
    host: ' Big Data',
    rating: ' Machine Learning',
    duration: ' Engineering & Computer Science. Master Linear Algebra"',
    lectures: 'Kashif Altaf',
    level: '4.4',
    url: '18 total hours',
  },
  {
    name: 'Data Science & Machine Learning(Theory+Projects)A-Z 90 HOURS',
    price: '455',
    description:
      '"Data Science & Machine Learning with Python for Beginners-Learn Statistics',
    host: ' Preprocessing & Reinforcement Learning"',
    rating: '"AI Sciences',
    duration: ' AI Sciences Team"',
    lectures: '4.4',
    level: '92.5 total hours',
    url: '644 lectures',
  },
  {
    name: '"Learn Data Science -Statistics',
    price: 'Machine Learning & NLP-Python"',
    description: '455',
    host: '"Learn Data Science from the basics of Statistics',
    rating: ' Mathematics ',
    duration: 'Machine Learning & NLP with Python"',
    lectures: 'Srini E',
    level: '4.4',
    url: '20 total hours',
  },
  {
    name: 'Data Science and Machine Learning Masterclass with R',
    price: '455',
    description: '"Data Science by IITan - Data Science :Data Manipulation ',
    host: ' Data Science Data Visualization',
    rating: ' Data Science : Data Analytics"',
    duration: 'Up Degree',
    lectures: '4.4',
    level: '15 total hours',
    url: '152 lectures',
  },
  {
    name: 'SQL & Database Design A-Z�: Learn MS SQL Server + PostgreSQL',
    price: '"1',
    description: '920"',
    host: 'Learn Both SQL Server & PostgreSQL By Doing. Enhance Your Data Analytics Career With Real World Data Science Exercises',
    rating: '"Kirill Eremenko',
    duration: ' Ilya Eremenko',
    lectures: ' Ligency Team"',
    level: '4.4',
    url: '12.5 total hours',
  },
  {
    name: 'The Complete NumPy course For Data Science : Hands-on NumPy',
    price: '455',
    description:
      'Learn first step towards Data Science with all important concept of Numerical Python NumPy in Python For Data Science',
    host: 'Data Science & Machine Learning Academy',
    rating: '4.4',
    duration: '3 total hours',
    lectures: '30 lectures',
    level: 'Intermediate',
    url: 'https://www.udemy.com/course/numpy-course/\r',
  },
  {
    name: 'The Complete Machine Learning and Data Science Course in R',
    price: '455',
    description:
      'Become a real time professional Data Scientist by learning the intuition and Math Behind each Machine Learning Model',
    host: 'Data Science Academy',
    rating: '4.4',
    duration: '17.5 total hours',
    lectures: '146 lectures',
    level: 'All Levels',
    url: 'https://www.udemy.com/course/the-complete-machine-learning-and-data-science-course-in-r/\r',
  },
  {
    name: 'Master Data Science with Python in 10 Hours | 2021',
    price: '455',
    description: '"Learn Python',
    host: ' its libraries for Data Science (Pandas',
    rating: 'Matplotlib',
    duration: 'Seaborn) and data pre-processing for Machine Learning!"',
    lectures: '"Berk Hakbilen',
    level: ' Tarik Sahin"',
    url: '4.4',
  },
  {
    name: 'From 0 to 1 : Spark for Data Science with Python',
    price: '455',
    description: '"Get your data to fly using Spark for analytics',
    host: ' machine learning and data science"',
    rating: 'Loony Corn',
    duration: '4.4',
    lectures: '8.5 total hours',
    level: '54 lectures',
    url: 'All Levels',
  },
  {
    name: '2021 R 4.0 Programming for Data Science || Beginners to Pro',
    price: '618',
    description: '"Learn Latest R 4 with R-Studio & Jupyter. DataFrame',
    host: ' Vectors',
    rating: ' Matrix',
    duration: ' DateTime',
    lectures: ' GGplot2',
    level: ' Tidyverse',
    url: ' Plotly',
  },
  {
    name: 'Statistics Masterclass for Data Science and Data Analytics',
    price: '455',
    description: '"Build a Solid Foundation of Statistics for Data Science',
    host: ' Learn Probability',
    rating: ' Distributions',
    duration: ' Hypothesis Testing',
    lectures: ' and More!"',
    level: 'Vijay Gadhave',
    url: '4.4',
  },
  {
    name: 'Python for Data Science',
    price: '455',
    description: 'Hands on to the most powerful language.',
    host: 'Saheb Singh Chaddha',
    rating: '4.4',
    duration: '3 total hours',
    lectures: '21 lectures',
    level: 'All Levels',
    url: 'https://www.udemy.com/course/python4ds/\r',
  },
  {
    name: 'Professional Certificate in Data Science',
    price: '455',
    description:
      '"Learn All the Skills to Become a Data Scientist [ Machine Learning',
    host: 'Deep Learning',
    rating: ' CNN',
    duration: ' DCGAN',
    lectures: ' Python',
    level: ' Java',
    url: ' Algorithms]"',
  },
  {
    name: '"DataScience-Stats',
    price: 'MachineLearning',
    description: 'NLP-Python-R-BigData-Spark"',
    host: '566',
    rating: '"Learn Data Science from basics of Stats',
    duration: 'Machine Learning',
    lectures: 'NLP',
    level: 'DeepLearning using Python',
    url: 'R',
  },
  {
    name: 'Data Science with R and Python',
    price: '455',
    description:
      '"Python or R programming! Learn data science with R & Python with all in one course. You\'ll learn NumPy',
    host: ' Pandas and more"',
    rating: 'Oak Academy',
    duration: '4.4',
    lectures: '13 total hours',
    level: '82 lectures',
    url: 'All Levels',
  },
  {
    name: 'Data Science- Project Management Methodology - CRISP-DM',
    price: '455',
    description: 'End to End High Level Overview of Data Science & AI projects',
    host: '360DigiTMG Elearning',
    rating: '4.4',
    duration: '5 total hours',
    lectures: '33 lectures',
    level: 'All Levels',
    url: 'https://www.udemy.com/course/data-science-project-management-methodology-crisp-dm/\r',
  },
  {
    name: 'Geospatial Data Science with Python: GeoPandas',
    price: '455',
    description: 'Vector based geospatial analysis',
    host: 'Michael Miller',
    rating: '4.4',
    duration: '10 total hours',
    lectures: '51 lectures',
    level: 'Intermediate',
    url: 'https://www.udemy.com/course/geospatial-data-science-with-python-geopandas/\r',
  },
  {
    name: 'Data Science - Data Mining Unsupervised Learning R & Python',
    price: '"6',
    description: '400"',
    host: 'Become a Practical Data Scientist',
    rating: '360DigiTMG Elearning',
    duration: '4.4',
    lectures: '2 total hours',
    level: '10 lectures',
    url: 'All Levels',
  },
  {
    name: '[2021] Learn Python for Data Science A-Z | Ver 5.9',
    price: '455',
    description:
      '"Programming In Python For Data Science. Learn how to use NumPy',
    host: ' Pandas',
    rating: ' Seaborn',
    duration: ' Matplotlib',
    lectures: ' Plotly',
    level: ' and more!"',
    url: 'Avinaash Guptaa',
  },
  {
    name: 'Machine Learning A-Z�: Hands-On Python & R In Data Science',
    price: '455',
    description:
      'Learn to create Machine Learning Algorithms in Python and R from two Data Science experts. Code templates included.',
    host: '"Kirill Eremenko',
    rating: ' Hadelin de Ponteves',
    duration: ' SuperDataScience Support',
    lectures: ' Ligency Team"',
    level: '4.5',
    url: '44.5 total hours',
  },
  {
    name: 'Data Science A-Z�: Real-Life Data Science Exercises Included',
    price: '468',
    description:
      '"Learn Data Science step by step through real Analytics examples. Data Mining',
    host: ' Modeling',
    rating: ' Tableau Visualization and more!"',
    duration: '"Kirill Eremenko',
    lectures: ' Ligency Team"',
    level: '4.5',
    url: '21 total hours',
  },
  {
    name: 'Statistics for Business Analytics and Data Science A-Z�',
    price: '618',
    description:
      '"Learn The Core Stats For A Data Science Career. Master Statistical Significance',
    host: ' Confidence Intervals And Much More!"',
    rating: '"Kirill Eremenko',
    duration: ' Ligency Team"',
    lectures: '4.5',
    level: '6 total hours',
    url: '42 lectures',
  },
  {
    name: 'Deep Learning A-Z�: Hands-On Artificial Neural Networks',
    price: '455',
    description:
      'Learn to create Deep Learning Algorithms in Python from two Machine Learning & Data Science experts. Templates included.',
    host: '"Kirill Eremenko',
    rating: ' Hadelin de Ponteves',
    duration: ' Ligency Team"',
    lectures: '4.5',
    level: '22.5 total hours',
    url: '173 lectures',
  },
  {
    name: 'Power BI A-Z: Hands-On Power BI Training For Data Science!',
    price: '455',
    description:
      'Learn Microsoft Power BI for Data Science and Data Analytics. Build visualizations and BI reports with Power BI Desktop',
    host: '"Kirill Eremenko',
    rating: ' Ligency Team"',
    duration: '4.5',
    lectures: '4.5 total hours',
    level: '44 lectures',
    url: 'All Levels',
  },
  {
    name: 'DP-100: A-Z Machine Learning using Azure Machine Learning',
    price: '455',
    description:
      'Microsoft Azure DP-100: Designing and Implementing a Data Science Solution Exam Covered. Learn Azure Machine Learning',
    host: '"Python',
    rating: ' Data Science & Machine Learning A-Z Team"',
    duration: '4.5',
    lectures: '29 total hours',
    level: '243 lectures',
    url: 'All Levels',
  },
  {
    name: 'Careers in Data Science A-Z�',
    price: '455',
    description:
      '"How to Become a Top Level Data Scientist - Learn What to Expect',
    host: ' How to be Prepared',
    rating: ' How to Stand Out and More..."',
    duration: '"Kirill Eremenko',
    lectures: ' Hadelin de Ponteves',
    level: ' Ligency Team"',
    url: '4.5',
  },
  {
    name: 'Intro to Data Science: Your Step-by-Step Guide To Starting',
    price: '618',
    description: '"Learn the critical elements of Data Science',
    host: ' from visualization to databases to Python and more',
    rating: ' in just 6 weeks!"',
    duration: '"Kirill Eremenko',
    lectures: ' Hadelin de Ponteves',
    level: ' Ligency Team"',
    url: '4.5',
  },
  {
    name: 'The Product Management for AI & Data Science Course 2021',
    price: '455',
    description:
      'The Complete Course for Becoming a Successful Product Manager in the Field of AI & Data Science',
    host: '"365 Careers',
    rating: ' Danielle Th�"',
    duration: '4.5',
    lectures: '5 total hours',
    level: '67 lectures',
    url: 'All Levels',
  },
  {
    name: 'TABLEAU 2018: Hands-On Tableau Training For Data Science!',
    price: '455',
    description:
      'Learn Tableau for Data Science step-by-step. Real-Life Data Analytics Exercises & Quizzes Included. Learn by doing!',
    host: '"Kirill Eremenko',
    rating: ' Ligency Team"',
    duration: '4.5',
    lectures: '8 total hours',
    level: '75 lectures',
    url: 'All Levels',
  },
  {
    name: 'RA: Data Science and Supply Chain analytics. A-Z with Python',
    price: '455',
    description: '"Learn Python',
    host: ' Supply Chain Data Science ',
    rating: 'Linear Programming',
    duration: ' Forecasting',
    lectures: ' Pricing and Inventory Management."',
    level: 'Haytham Omar',
    url: '4.5',
  },
  {
    name: 'Data Science : Master Machine Learning Without Coding',
    price: '455',
    description:
      'Learn Fundamentals Of Data Science & Machine Learning With Rapidminer (No Coding). Dataset & Solutions Included.',
    host: 'Ram Prasad',
    rating: '4.5',
    duration: '2.5 total hours',
    lectures: '63 lectures',
    level: 'Beginner',
    url: 'https://www.udemy.com/course/hands-on-machine-learning-without-writing-code/\r',
  },
  {
    name: 'Data Science with Python Course : Hands-on Data Science 2021',
    price: '455',
    description: '"Numpy',
    host: ' Pandas',
    rating: ' Matplotlib',
    duration: ' Scikit-Learn',
    lectures: ' WebScraping',
    level: ' Data Science',
    url: ' Machine Learning',
  },
  {
    name: 'End to End Data Science Practicum with Knime',
    price: '455',
    description:
      'Applied Data Science Concepts and Techniques with Knime and hands on examples',
    host: 'Prof. Dr. ?adi Evren ?eker',
    rating: '4.5',
    duration: '9 total hours',
    lectures: '72 lectures',
    level: 'All Levels',
    url: 'https://www.udemy.com/course/datascience-knime/\r',
  },
  {
    name: 'Data Science and Machine Learning Developer Certification',
    price: '455',
    description:
      'Learn the powerful tools used in data science and machine learning from a top instructor',
    host: '"Starweaver Team',
    rating: ' Paul Siegel"',
    duration: '4.5',
    lectures: '12 total hours',
    level: '57 lectures',
    url: 'Intermediate',
  },
  {
    name: 'Mathematics Linear Algebra for Machine Learning Data Science',
    price: '455',
    description:
      '"Master the Complete linear algebra - Mathematics for data science',
    host: ' machine learning & Deep Learning - Practical exercise"',
    rating: 'Manifold AI Learning �',
    duration: '4.5',
    lectures: '13 total hours',
    level: '117 lectures',
    url: 'All Levels',
  },
  {
    name: 'Data Science 2021: Data Science & Machine Learning in Python',
    price: '455',
    description: '"Data Science',
    host: ' Machine Learning Python',
    rating: ' Deep Learning',
    duration: ' TensorFlow 2.0',
    lectures: ' NLP',
    level: ' Statistics for Data Science',
    url: ' Data Analysis !"',
  },
  {
    name: 'Data Science:Hands-on Covid19 Face Mask Detection-CNN&OpenCV',
    price: '455',
    description:
      'A Practical Hands-on Data Science Guided Project on Covid-19 Face Mask Detection using Deep Learning & OpenCV',
    host: 'School of Disruptive Innovation',
    rating: '4.5',
    duration: '2 total hours',
    lectures: '10 lectures',
    level: 'All Levels',
    url: 'https://www.udemy.com/course/data-science-hands-on-covid19-face-mask-detection-cnn-opencv/\r',
  },
  {
    name: 'Data Science:Data Mining & Natural Language Processing in R',
    price: '455',
    description:
      '"Harness the Power of Machine Learning in R for Data/Text Mining',
    host: ' & Natural Language Processing with Practical Examples"',
    rating: 'Minerva Singh',
    duration: '4.5',
    lectures: '13 total hours',
    level: '110 lectures',
    url: 'All Levels',
  },
  {
    name: '"Intro to Big Data',
    price: ' Data Science and Artificial Intelligence"',
    description: '455',
    host: '"Big Data Technology & Tools for Non-Technical Leaders. Industry expert insights on IoT',
    rating: ' AI and Machine Learning for all."',
    duration: 'Julia Mariasova',
    lectures: '4.5',
    level: '3.5 total hours',
    url: '80 lectures',
  },
  {
    name: '"Python + SQL + Tableau: Integrating Python',
    price: ' SQL',
    description: ' and Tableau"',
    host: '455',
    rating:
      '"See the full picture: Learn how to combine the three most important tools in data science: Python',
    duration: ' SQL',
    lectures: ' and Tableau"',
    level: '365 Careers',
    url: '4.5',
  },
  {
    name: 'Python for Data Science and Visualization -Beginners to Pro',
    price: '455',
    description:
      '"Complete Python data science course - beginner to expert in data analysis and visualization - Pandas',
    host: ' Numpy & MatPlotLib"',
    rating: '"Analytics Leap',
    duration: ' Animesh Jaipurkar"',
    lectures: '4.5',
    level: '5 total hours',
    url: '69 lectures',
  },
  {
    name: 'Python for Data Science: Master NumPy & Pandas on Real Data',
    price: '455',
    description: '"Master the power of NumPy',
    host: ' Pandas and Python built-in data structures by real life datasets. All dataset included."',
    rating: 'Rune Thomsen',
    duration: '4.5',
    lectures: '6.5 total hours',
    level: '90 lectures',
    url: 'Beginner',
  },
  {
    name: 'Data Science:Hands-on Covid-19 Data Analysis & Visualization',
    price: '455',
    description:
      'Data Science : A practical Hands-on project on Covid-19 Data Analysis and Visualization using Plotly Express (45 graphs)',
    host: 'School of Disruptive Innovation',
    rating: '4.5',
    duration: '2 total hours',
    lectures: '15 lectures',
    level: 'All Levels',
    url: 'https://www.udemy.com/course/hands-on-covid-19-data-visualization-using-plotly-express/\r',
  },
  {
    name: 'Introduction to Python for Data Science',
    price: '455',
    description:
      'Learn everything you need to know in Python programming to start your Data Science journey.',
    host: 'Jedha Bootcamp',
    rating: '4.5',
    duration: '3.5 total hours',
    lectures: '47 lectures',
    level: 'Beginner',
    url: 'https://www.udemy.com/course/introduction-to-python-for-data-science/\r',
  },
  {
    name: 'Learn Python For Data Science W/ Search & Recommender Algos!',
    price: '"2',
    description: '560"',
    host: '"Practice hands-on text mining with no prior coding skills! Learn basic keyword extraction',
    rating: ' search',
    duration: ' and recommendation."',
    lectures: 'Larry Wai',
    level: '4.5',
    url: '4.5 total hours',
  },
  {
    name: '"R for Data Analysis',
    price: ' Statistics and Data Science"',
    description: '455',
    host: '"Data Analysis & Data Science using R : Descriptive & Inferential Statistics',
    rating: ' Data Visualization',
    duration: ' Hypothesis Testing"',
    lectures: 'Syed Mohiuddin',
    level: '4.5',
    url: '8 total hours',
  },
  {
    name: 'The Data Science Course 2021: Complete Data Science Bootcamp',
    price: '455',
    description: '"Complete Data Science Training: Mathematics',
    host: ' Statistics',
    rating: ' Python',
    duration: ' Advanced Statistics in Python',
    lectures: ' Machine & Deep Learning"',
    level: '"365 Careers',
    url: ' 365 Careers Team"',
  },
  {
    name: 'Tableau 2020 A-Z: Hands-On Tableau Training for Data Science',
    price: '455',
    description:
      'Learn Tableau 2020 for data science step by step. Real-life data analytics exercises & quizzes included. Learn by doing!',
    host: '"Kirill Eremenko',
    rating: ' Ligency Team"',
    duration: '4.6',
    lectures: '9 total hours',
    level: '82 lectures',
    url: 'All Levels',
  },
  {
    name: 'R Programming A-Z�: R For Data Science With Real Exercises!',
    price: '455',
    description: '"Learn Programming In R And R Studio. Data Analytics',
    host: ' Data Science',
    rating: ' Statistical Analysis',
    duration: ' Packages',
    lectures: ' Functions',
    level: ' GGPlot2"',
    url: '"Kirill Eremenko',
  },
  {
    name: '"Machine Learning',
    price: ' Data Science and Deep Learning with Python"',
    description: '455',
    host: '"Complete hands-on machine learning tutorial with data science',
    rating: ' Tensorflow',
    duration: ' artificial intelligence',
    lectures: ' and neural networks"',
    level: '"Sundog Education by Frank Kane',
    url: ' Frank Kane"',
  },
  {
    name: 'Python A-Z�: Python For Data Science With Real Exercises!',
    price: '455',
    description:
      '"Programming In Python For Data Analytics And Data Science. Learn Statistical Analysis',
    host: ' Data Mining And Visualization"',
    rating: '"Kirill Eremenko',
    duration: ' Ligency Team"',
    lectures: '4.6',
    level: '11 total hours',
    url: '75 lectures',
  },
  {
    name: 'Bayesian Machine Learning in Python: A/B Testing',
    price: '455',
    description: '"Data Science',
    host: ' Machine Learning',
    rating: ' and Data Analytics Techniques for Marketing',
    duration: ' Digital Media',
    lectures: ' Online Advertising',
    level: ' and More"',
    url: 'Lazy Programmer Inc.',
  },
  {
    name: 'Cluster Analysis and Unsupervised Machine Learning in Python',
    price: '455',
    description: '"Data science techniques for pattern recognition',
    host: ' data mining',
    rating: ' k-means clustering',
    duration: ' and hierarchical clustering',
    lectures: ' and KDE."',
    level: '"Lazy Programmer Team',
    url: ' Lazy Programmer Inc."',
  },
  {
    name: 'R Programming for Statistics and Data Science 2021',
    price: '455',
    description:
      'R Programming for Data Science & Data Analysis. Applying R for Statistics and Data Visualization with GGplot2 in R',
    host: '"365 Careers',
    rating: ' 365 Simona (The 365 Team)"',
    duration: '4.6',
    lectures: '6.5 total hours',
    level: '126 lectures',
    url: 'All Levels',
  },
  {
    name: 'Complete 2020 Data Science & Machine Learning Bootcamp',
    price: '455',
    description: '"Learn Python',
    host: ' Tensorflow',
    rating: ' Deep Learning',
    duration: ' Regression',
    lectures: ' Classification',
    level: ' Neural Networks',
    url: ' Artificial Intelligence & more!"',
  },
  {
    name: 'Probability and Statistics for Business and Data Science',
    price: '455',
    description:
      'Learn how to apply probability and statistics to real data science and business applications!',
    host: 'Jose Portilla',
    rating: '4.6',
    duration: '5 total hours',
    lectures: '53 lectures',
    level: 'All Levels',
    url: 'https://www.udemy.com/course/probability-and-statistics-for-business-and-data-science/\r',
  },
  {
    name: 'Deep Learning Prerequisites: Logistic Regression in Python',
    price: '468',
    description: '"Data science',
    host: ' machine learning',
    rating:
      ' and artificial intelligence in Python for students and professionals"',
    duration: 'Lazy Programmer Inc.',
    lectures: '4.6',
    level: '6.5 total hours',
    url: '59 lectures',
  },
  {
    name: 'Data Science Career Guide - Interview Preparation',
    price: '455',
    description:
      'Prepare for your Data Science Interview with this full guide on a career in Data Science including practice questions!',
    host: 'Jose Portilla',
    rating: '4.6',
    duration: '4 total hours',
    lectures: '110 lectures',
    level: 'All Levels',
    url: 'https://www.udemy.com/course/data-science-career-guide-interview-preparation/\r',
  },
  {
    name: 'Data Science 2021 : Complete Data Science & Machine Learning',
    price: '455',
    description: '"Machine Learning A-Z',
    host: ' Data Science',
    rating: ' Python for Machine Learning',
    duration: ' Math for Machine Learning',
    lectures: ' Statistics for Data Science"',
    level: '"Python',
    url: ' Data Science & Machine Learning A-Z Team"',
  },
  {
    name: '2021 Data Science & Machine Learning with R from A-Z Course',
    price: '455',
    description:
      '"Become a professional Data Scientist with R and learn Machine Learning',
    host: ' Data Analysis + Visualization',
    rating: ' Web Apps + more!"',
    duration: '"Juan E. Galvan',
    lectures: ' Ismail Tigrek"',
    level: '4.6',
    url: '28.5 total hours',
  },
  {
    name: 'Statistics & Mathematics for Data Science & Data Analytics',
    price: '455',
    description:
      'Learn the statistics & probability for data science and business analysis',
    host: 'Nikolai Schuler',
    rating: '4.6',
    duration: '11.5 total hours',
    lectures: '90 lectures',
    level: 'Beginner',
    url: 'https://www.udemy.com/course/statistics-for-data-science-data-analytics/\r',
  },
  {
    name: 'SQL For Data Science With Google Big Query',
    price: '455',
    description: '"Learn SQL for Data Visualization',
    host: ' Data Analysis',
    rating: ' and Data Science Using Google Cloud Platform"',
    duration: 'Chris Levy',
    lectures: '4.6',
    level: '7 total hours',
    url: '57 lectures',
  },
  {
    name: 'Data Science and Machine Learning using Python - A Bootcamp',
    price: '455',
    description:
      'Numpy Pandas Matplotlib Seaborn Ploty Machine Learning Scikit-Learn Data Science Recommender system NLP Theory Hands-on',
    host: '"Dr. Junaid Qazi',
    rating: ' PhD"',
    duration: '4.6',
    lectures: '25 total hours',
    level: '111 lectures',
    url: 'All Levels',
  },
  {
    name: '"Full Stack Data Science with Python',
    price: ' Numpy and R Programming"',
    description: '455',
    host: '"Learn data science with R programming and Python. Use NumPy',
    rating: ' Pandas to manipulate the data and produce outcomes"',
    duration: 'Oak Academy',
    lectures: '4.6',
    level: '20 total hours',
    url: '151 lectures',
  },
  {
    name: 'RA: Data Science and Supply chain analytics.(A-Z with R)',
    price: '455',
    description: '"Learn R',
    host: 'Supply-chain Data Science',
    rating: ' Inventory Optimization',
    duration: 'Big Data forecasting',
    lectures: ' Machine learning and Revenue Management."',
    level: 'Haytham Omar',
    url: '4.6',
  },
  {
    name: 'Statistics for Data Analysis Using R',
    price: '455',
    description: '"Learn Programming in R & R Studio � Descriptive',
    host: ' Inferential Statistics � Plots for Data Visualization � Data Science"',
    rating: 'Sandeep Kumar �',
    duration: '4.6',
    lectures: '12.5 total hours',
    level: '110 lectures',
    url: 'All Levels',
  },
  {
    name: 'Python for Data Science: Learn Data Science From Scratch',
    price: '455',
    description: '"Data Science with Python. Use NumPy',
    host: ' Pandas',
    rating:
      ' Matplotlib with hands-on projects and learn Python for Data Science with us"',
    duration: 'Oak Academy',
    lectures: '4.6',
    level: '9.5 total hours',
    url: '51 lectures',
  },
  {
    name: 'Data Science Real-World Use Cases - Hands On Python',
    price: '455',
    description: '"Solve 3 real Business Problems',
    host: ' Build Robust AI',
    rating: ' Ml ',
    duration: ' NLP and Time Series models in Real World Scenarios.."',
    lectures: 'Shan Singh',
    level: '4.6',
    url: '11 total hours',
  },
  {
    name: 'Data Science With Python!',
    price: '455',
    description: 'Test Studies in Data Science',
    host: 'Matthew Fried',
    rating: '4.6',
    duration: '19 total hours',
    lectures: '108 lectures',
    level: 'All Levels',
    url: 'https://www.udemy.com/course/python-for-all-with-a-focus-on-financial-applications/\r',
  },
  {
    name: 'Causal Data Science with Directed Acyclic Graphs',
    price: '455',
    description:
      '"Get to know the modern tools for causal inference from machine learning and AI',
    host: ' with many practical examples in R"',
    rating: 'Paul H�nermund',
    duration: '4.6',
    lectures: '5 total hours',
    level: '27 lectures',
    url: 'All Levels',
  },
  {
    name: 'Data Science: Bitcoin Data Visualization & Price Prediction',
    price: '455',
    description:
      'Data Science: Hands-on & Practical Cryptocurrency Data Visualization & Bitcoin Price Forecasting using Machine Learning',
    host: 'School of Disruptive Innovation',
    rating: '4.6',
    duration: '1.5 total hours',
    lectures: '14 lectures',
    level: 'Beginner',
    url: 'https://www.udemy.com/course/cryptocurrency-data-visualization-bitcoin-price-prediction/\r',
  },
  {
    name: 'Data Science Projects with Python',
    price: '455',
    description:
      '"A case study approach to successful data science projects using Python',
    host: ' pandas',
    rating: ' and scikit-learn"',
    duration: 'Packt Publishing',
    lectures: '4.6',
    level: '6.5 total hours',
    url: '63 lectures',
  },
  {
    name: 'Data science on COVID-19 / CORONA virus spread data',
    price: '455',
    description:
      '"Analysis of CORONA / COVID-19 virus data with Python: data handling',
    host: ' machine learning',
    rating: ' visualisation',
    duration: ' spread simulations"',
    lectures: 'Frank Kienle',
    level: '4.6',
    url: '7 total hours',
  },
  {
    name: 'Complete Machine Learning & Data Science Bootcamp 2021',
    price: '455',
    description: '"Learn Data Science',
    host: ' Data Analysis',
    rating:
      ' Machine Learning (Artificial Intelligence) and Python with Tensorflow',
    duration: ' Pandas & more!"',
    lectures: '"Andrei Neagoie',
    level: ' Daniel Bourke"',
    url: '4.7',
  },
  {
    name: 'Data Science and Machine Learning Bootcamp with R',
    price: '618',
    description:
      'Learn how to use the R programming language for data science and machine learning and data visualization!',
    host: 'Jose Portilla',
    rating: '4.7',
    duration: '18 total hours',
    lectures: '128 lectures',
    level: 'All Levels',
    url: 'https://www.udemy.com/course/data-science-and-machine-learning-bootcamp-with-r/\r',
  },
  {
    name: 'Tableau 20 Advanced Training: Master Tableau in Data Science',
    price: '455',
    description:
      'Master Tableau 20 in Data Science by solving Real-Life Analytics Problems. Learn Visualisation and Data Mining by doing!',
    host: '"Kirill Eremenko',
    rating: ' Ligency Team"',
    duration: '4.7',
    lectures: '10 total hours',
    level: '74 lectures',
    url: 'Intermediate',
  },
  {
    name: '100 Days of Code - The Complete Python Pro Bootcamp for 2021',
    price: '618',
    description:
      '"Master Python by building 100 projects in 100 days. Learn to build websites',
    host: ' games',
    rating: ' apps',
    duration: ' plus scraping and data science"',
    lectures: 'Dr. Angela Yu',
    level: '4.7',
    url: '63.5 total hours',
  },
  {
    name: 'R Programming: Advanced Analytics In R For Data Science',
    price: '455',
    description:
      '"Take Your R & R Studio Skills To The Next Level. Data Analytics',
    host: ' Data Science',
    rating: ' Statistical Analysis in Business',
    duration: ' GGPlot2"',
    lectures: '"Kirill Eremenko',
    level: ' Ligency Team"',
    url: '4.7',
  },
  {
    name: '2021 Python for Machine Learning & Data Science Masterclass',
    price: '455',
    description:
      '"Learn about Data Science and Machine Learning with Python! Including Numpy',
    host: ' Pandas',
    rating: ' Matplotlib',
    duration: ' Scikit-Learn and more!"',
    lectures: 'Jose Portilla',
    level: '4.7',
    url: '40 total hours',
  },
  {
    name: 'Python for Excel: Use xlwings for Data Science and Finance',
    price: '455',
    description:
      '"Integrate Excel and Python and get the best of two Worlds! Python Beginners welcome. Use Pandas',
    host: ' Seaborn & co. in Excel"',
    rating: 'Alexander Hagmann',
    duration: '4.7',
    lectures: '16 total hours',
    level: '195 lectures',
    url: 'All Levels',
  },
  {
    name: '"Ensemble Machine Learning in Python: Random Forest',
    price: ' AdaBoost"',
    description: '618',
    host: '"Ensemble Methods: Boosting',
    rating: ' Bagging',
    duration: ' Boostrap',
    lectures: ' and Statistical Machine Learning for Data Science in Python"',
    level: '"Lazy Programmer Team',
    url: ' Lazy Programmer Inc."',
  },
  {
    name: 'TABLEAU 2018 ADVANCED: Master Tableau in Data Science',
    price: '455',
    description:
      'Master Tableau in Data Science by solving Real-Life Analytics Problems. Learn Visualisation and Data Mining by doing!',
    host: '"Kirill Eremenko',
    rating: ' Ligency Team"',
    duration: '4.7',
    lectures: '9.5 total hours',
    level: '72 lectures',
    url: 'Intermediate',
  },
  {
    name: 'Deep Learning: Convolutional Neural Networks in Python',
    price: '455',
    description: '"Use CNNs for Image Recognition',
    host: ' Natural Language Processing (NLP) +More! For Data Science',
    rating: ' Machine Learning',
    duration: ' and AI"',
    lectures: 'Lazy Programmer Inc.',
    level: '4.7',
    url: '12 total hours',
  },
  {
    name: 'Python Coding MADE EASY : A Python Coding Course in Python 3',
    price: '455',
    description:
      'Python coding for beginners. Python coding for Data Science. AI Python. Web Python. Business Python. Engineering Python.',
    host: 'Cher Hin Chong',
    rating: '4.7',
    duration: '2 total hours',
    lectures: '20 lectures',
    level: 'Beginner',
    url: 'https://www.udemy.com/course/python-programming-tutorial-a-z/\r',
  },
  {
    name: 'Data Science in Action using Python',
    price: '455',
    description:
      'Gain hands-on experience in building a Data Driven AI engagement using Python',
    host: 'Neena Sathi',
    rating: '4.7',
    duration: '7.5 total hours',
    lectures: '43 lectures',
    level: 'All Levels',
    url: 'https://www.udemy.com/course/data-science-in-action-using-python/\r',
  },
  {
    name: 'R for Data Science: Learn R Programming in 2 Hours',
    price: '455',
    description:
      'Enter the world of R Programming: Everything you need to get started with R and Data Science in just 2 HOURS!',
    host: 'Ajay R Warrier',
    rating: '4.7',
    duration: '2 total hours',
    lectures: '34 lectures',
    level: 'Beginner',
    url: 'https://www.udemy.com/course/r-for-data-science-learn-r-programming-in-2-hours/\r',
  },
  {
    name: 'Data Science for Professionals',
    price: '455',
    description: "It's time to leave spreadsheets behind...",
    host: 'Gregory Sward',
    rating: '4.7',
    duration: '6.5 total hours',
    lectures: '33 lectures',
    level: 'Beginner',
    url: 'https://www.udemy.com/course/data-science-for-professionals/\r',
  },
  {
    name: 'R for Data Science: R Programming Bootcamp',
    price: '455',
    description: '"Learn R Programming Fundamentals',
    host: ' Data Wrangling',
    rating: ' Data Visualization for Data Science"',
    duration: 'Syed Mohiuddin',
    lectures: '4.7',
    level: '6 total hours',
    url: '82 lectures',
  },
  {
    name: 'The Complete Python 3 Masterclass - From Beginner To Pro',
    price: '455',
    description: '"Python for beginners',
    host: ' Learn Python Programming and build your own Python programs: Data Science',
    rating: ' Machine Learning',
    duration: ' etc."',
    lectures: '"Denis Panjuta',
    level: ' Jannis Seemann',
    url: ' Tutorials.eu by Denis Panjuta"',
  },
  {
    name: '"Python Beyond Basics for Machine Learning',
    price: ' Data Science',
    description: ' AI"',
    host: '455',
    rating: '"Data Science',
    duration: ' Machine Learning and Artificial Intelligence with Python"',
    lectures: 'Piyush Dave',
    level: '4.7',
    url: '13.5 total hours',
  },
  {
    name: 'Python in a Weekend: The Easiest Python for Beginners Course',
    price: '455',
    description:
      '"Jump into Python by Building Your First 3 Python-Based Apps. Python = Data Science',
    host: ' Machine Learning',
    rating: ' App Development+"',
    duration: '"Nick Walter',
    lectures: ' Phil Ebiner',
    level: ' Video School"',
    url: '4.7',
  },
  {
    name: 'Machine Learning for Absolute Beginners - Level 2',
    price: '455',
    description:
      'Learn the Python Fundamentals and Pandas Library for Data Science Projects',
    host: 'Idan Gabrieli',
    rating: '4.7',
    duration: '4 total hours',
    lectures: '42 lectures',
    level: 'Beginner',
    url: 'https://www.udemy.com/course/machine-learning-for-absolute-beginners-level-2/\r',
  },
  {
    name: 'Data Science Project Planning',
    price: '618',
    description: 'Fundamental Concepts for Beginners',
    host: 'Gopinath Ramakrishnan',
    rating: '4.7',
    duration: '5 total hours',
    lectures: '56 lectures',
    level: 'Beginner',
    url: 'https://www.udemy.com/course/data-science-project-planning/\r',
  },
  {
    name: 'Tableau for Data Science with R & Python Integration',
    price: '455',
    description:
      'Master Data Visualization and Improve Your Data Science Skills with Tableau Desktop integrated with R and Python',
    host: 'Candas Bilgin',
    rating: '4.7',
    duration: '5.5 total hours',
    lectures: '38 lectures',
    level: 'All Levels',
    url: 'https://www.udemy.com/course/tableau-desktop-advanced/\r',
  },
  {
    name: 'Ultimate Data Science Bootcamp in Python with 5 Projects',
    price: '455',
    description:
      'Master Data Science and Machine Learning with Python and complete 5 Data Science Capstone Projects',
    host: 'Data is Good',
    rating: '4.8',
    duration: '15 total hours',
    lectures: '258 lectures',
    level: 'All Levels',
    url: 'https://www.udemy.com/course/data-science-bootcamp-with-python/\r',
  },
  {
    name: 'How to Start a Career in Data Science 2021',
    price: '455',
    description:
      '"The Ultimate Guide to Starting a Data Science Career: Create a Project Portfolio',
    host: ' Build Your Resume',
    rating: ' Get an Interview"',
    duration: '"365 Careers',
    lectures: ' Ken Jee"',
    level: '4.8',
    url: '4.5 total hours',
  },
  {
    name: 'Machine Learning and AI: Support Vector Machines in Python',
    price: '455',
    description:
      'Artificial Intelligence and Data Science Algorithms in Python for Classification and Regression',
    host: '"Lazy Programmer Team',
    rating: ' Lazy Programmer Inc."',
    duration: '4.8',
    lectures: '9 total hours',
    level: '73 lectures',
    url: 'Expert',
  },
  {
    name: 'Complete Python + Django + Data Science course',
    price: '455',
    description: '"Python Fundamentals',
    host: ' OOP',
    rating: ' Data Science',
    duration: ' Django and more!"',
    lectures: 'YouRa Allakhverdov',
    level: '4.8',
    url: '38 total hours',
  },
  {
    name: 'R Programming for Data Science and Machine Learning',
    price: '"1',
    description: '920"',
    host: '"Learn R Programming Language for Data Science',
    rating: ' Machine Learning',
    duration: ' Data Analysis and Data Visualization with Libraries"',
    lectures: 'The Tech X Learners',
    level: '4.8',
    url: '7.5 total hours',
  },
  {
    name: 'Complete Python for data science and cloud computing',
    price: '455',
    description:
      'A complete & in-depth use case course taught by data science PHD & business consultants with thousand examples',
    host: 'Datagist INC',
    rating: '4.8',
    duration: '49 total hours',
    lectures: '361 lectures',
    level: 'All Levels',
    url: 'https://www.udemy.com/course/complete-python-for-data-science-and-cloud-computing/\r',
  },
  {
    name: 'Data Science Job: How to become a Data Scientist',
    price: '455',
    description: 'Find your first job as a Data Scientist.',
    host: 'Przemek Chojecki',
    rating: '4.8',
    duration: '1 total hour',
    lectures: '7 lectures',
    level: 'Beginner',
    url: 'https://www.udemy.com/course/data-science-job-how-to-become-a-data-scientist/\r',
  },
  {
    name: 'Data science and Data preparation with KNIME',
    price: '455',
    description:
      'KNIME - a powerful tool for data science and machine learning Data science with higher efficiency. KNIME data cleaning',
    host: 'Dan We',
    rating: '4.8',
    duration: '4 total hours',
    lectures: '24 lectures',
    level: 'Beginner',
    url: 'https://www.udemy.com/course/data-science-and-data-preparation-with-knime/\r',
  },
  {
    name: 'R Programming for Data Science and Machine Learning',
    price: '455',
    description:
      'Learn R programming to implement Machine Learning & DS algorithms',
    host: '"Sunil Kumar Gupta',
    rating: ' DataQrious Academy"',
    duration: '4.8',
    lectures: '13.5 total hours',
    level: '84 lectures',
    url: 'Beginner',
  },
  {
    name: 'Statistical Thinking and Data Science with R.',
    price: '455',
    description: '"R from A-Z! Statistics',
    host: ' Advanced Regression',
    rating: 'Visualizations',
    duration: ' Probabilities',
    lectures: ' Inference',
    level: ' Simulations and Machine learning."',
    url: 'Haytham Omar',
  },
  {
    name: 'Data Science Quick Start: Focus On Correlation & Python',
    price: '455',
    description:
      'Make 2021 The Year To Get Started in Data Science: Learn The Rudiments of Correlation Analysis & Python.',
    host: 'Adam Ross Nelson',
    rating: '4.9',
    duration: '2.5 total hours',
    lectures: '25 lectures',
    level: 'Beginner',
    url: 'https://www.udemy.com/course/data-science-quick-start/\r',
  },
  {
    name: 'Data Science with SAP - Machine Learning for Enterprise Data',
    price: '455',
    description:
      '"An Ultimate Hands On Masterclass for Applying Machine Learning',
    host: ' Data Science techniques on SAP Data to derive insights"',
    rating: 'Manifold AI Learning �',
    duration: '5',
    lectures: '20 total hours',
    level: '184 lectures',
    url: 'All Levels',
  },
  {
    name: 'Python and Data Science from Scratch With RealLife Exercises',
    price: '455',
    description: '"Learn Data Science with Python programming. Use NumPy',
    host: ' Pandas',
    rating: ' Matplotlib and dive in Data Science with Python Examples"',
    duration: 'Oak Academy',
    lectures: '5',
    level: '12.5 total hours',
    url: '95 lectures',
  },
  { name: '' },
]

export default data
